[theme]
primaryColor = "#d71920"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7f7f7"
textColor = "#171717"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
headless = true
